const express = require("express");
const fs = require("fs");
const app = express();
const bodyParser = require('body-parser');
app.use(bodyParser.urlencoded({ extended : true } ));
app.use(express.static("public"));
app.get("/");
require('./app/routes')(app, fs);
app.listen(8080);
console.log("Server started");